browser = "chrome"
url = "https://demoqa.com/automation-practice-form"
# Xpaths
input_first_name = "//input[@id='firstName']"
input_last_name = "//input[@id='lastName']"
input_email = "//input[@id='userEmail']"
gender_m = "//label[contains(text(),'Male')]"
gender_f = "//label[contains(text(),'Female')]"
gender_o = "//label[contains(text(),'Other')]"
input_phone = "//input[@id='userNumber']"
input_date_of_birth = "//input[@id='dateOfBirthInput']"
input_subjects = "//body/div[@id='app']/div[1]/div[1]/div[2]/div[2]/div[1]/form[1]/div[6]/div[2]/div[1]/div[1]/div[1]"
hobbies_sports = "//label[contains(text(),'Sports')]"
hobbies_reading = "//label[contains(text(),'Reading')]"
hobbies_music = "//label[contains(text(),'Music')]"
fill_address = "//textarea[@id='currentAddress']"
state_combobox = "//body/div[@id='app']/div[1]/div[1]/div[2]/div[2]/div[1]/form[1]/div[10]/div[2]/div[1]/div[1]/div[2]/div[1]"

submit = "//button[@id='submit']"
