browser = "chrome"
url = "https://demoqa.com/automation-practice-form"
# Xpaths
input_first_name = "//input[@id='firstName']"
input_last_name = "//input[@id='lastName']"
input_email = "//input[@id='userEmail']"
gender_m = "//label[contains(text(),'Male')]"
gender_f = "//label[contains(text(),'Female')]"
gender_o = "//label[contains(text(),'Other')]"
input_phone = "//input[@id='userNumber']"
input_date_of_birth = "//input[@id='dateOfBirthInput']"
date_of_birth_year_drop_down = "//select[@class='react-datepicker__year-select']"
date_of_birth_month_drop_down = "//select[@class='react-datepicker__month-select']"
date_of_birth_day_drop_down = "//div[contains(@class, 'react-datepicker__week') and contains(.//div, '20') ]"
input_subjects = "//input[@id='subjectsInput']"
input_subjects_arts = "//div[contains(@class, 'subjects-auto-complete__option') and contains(string(), 'Arts') ]"
hobbies_sports = "//label[contains(text(),'Sports')]"
hobbies_reading = "//label[contains(text(),'Reading')]"
hobbies_music = "//label[contains(text(),'Music')]"
choose_file = "//input[@id='uploadPicture']"
file = "C:\\Users\\gmenezes\\Projects\\Student_Registration\\registration_form\\Tests\\Wallpaper.jpg"
fill_address = "//textarea[@id='currentAddress']"
state_combobox = "//*[@id='state']/div/div[1]"

submit = "//button[@id='submit']"
